# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [4]:
class Book:
  def __init__(self, title, author, pages, price):
    self.title = title
    self.author = author
    self.pages = pages
    # Use the set_price method to ensure price is numeric
    self.set_price(price)

  def get_price(self):
    return self.price

  def set_price(self, new_price):
    if isinstance(new_price, (int, float)):
      self.price = new_price
    else:
      try:
        self.price = float(new_price)
      except ValueError:
        print("Price must be a numeric value.")
        self.price = 0 # Default or handle error appropriately

In [2]:
b1 = Book("Practical Programming", "Gries, Campbell, Montojo", 383, 50)

In [3]:
b2 = Book("Building a Career in Data Science", "Robinson, Nolis", 322, 40)

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [6]:
class Phone:
  def __init__(self, model, id_num, name, brand, price):
    self.model = model
    self.id = id_num # Renamed 'id' to 'id_num' to avoid conflict with built-in 'id'
    self.name = name
    self.brand = brand
    self.set_price(price) # Use setter for price validation

  # Getters
  def get_model(self):
    return self.model

  def get_id(self):
    return self.id

  def get_name(self):
    return self.name

  def get_brand(self):
    return self.brand

  def get_price(self):
    return self.price

  # Setters
  def set_model(self, new_model):
    self.model = new_model

  def set_id(self, new_id):
    self.id = new_id

  def set_name(self, new_name):
    self.name = new_name

  def set_brand(self, new_brand):
    self.brand = new_brand

  def set_price(self, new_price):
    if isinstance(new_price, (int, float)):
      self.price = new_price
    else:
      try:
        self.price = float(new_price)
      except ValueError:
        print("Price must be a numeric value.")
        self.price = 0 # Default to 0 or handle error appropriately

  # Method to calculate total price with tax
  def calculate_total(self, tax_rate):
    if not isinstance(tax_rate, (int, float)) or tax_rate < 0:
      print("Tax rate must be a non-negative numeric value.")
      return None
    return self.price * (1 + tax_rate)



In [7]:
# Example usage (optional, for testing)
my_phone = Phone("iPhone 13 Pro", "XYZ123", "My Phone", "Apple", 999.99)
print(f"Phone brand: {my_phone.get_brand()}")
my_phone.set_price(1099.99)
print(f"New price: {my_phone.get_price()}")
print(f"Total with 8% tax: {my_phone.calculate_total(0.08)}")

Phone brand: Apple
New price: 1099.99
Total with 8% tax: 1187.9892


## Numpy

In [10]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [11]:
original_array = np.arange(6) # Creates a 1D array [0 1 2 3 4 5]
reshaped_array = original_array.reshape(2, 3) # Reshapes to 2 rows and 3 columns

print("Original Array:", original_array)
print("\nReshaped 2x3 Array:")
print(reshaped_array)

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:
[[0 1 2]
 [3 4 5]]


#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [12]:
true_array = np.ones((3, 3), dtype=bool)
print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### 3. Create a 1D array filled with zeros and another filled with ones

In [13]:
zeros_array = np.zeros(5) # Example: a 1D array of 5 zeros
ones_array = np.ones(5)  # Example: a 1D array of 5 ones

print("1D Array of Zeros:", zeros_array)
print("1D Array of Ones:", ones_array)

1D Array of Zeros: [0. 0. 0. 0. 0.]
1D Array of Ones: [1. 1. 1. 1. 1.]


#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [14]:
arr = np.arange(10)
reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Reversed Array: [9 8 7 6 5 4 3 2 1 0]


#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h_stacked_array = np.hstack((a, b))

print("Array a:", a)
print("Array b:", b)
print("Horizontally Stacked Array:", h_stacked_array)

Array a: [1 2 3]
Array b: [4 5 6]
Horizontally Stacked Array: [1 2 3 4 5 6]


#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Add two NumPy arrays element by element
sum_array = a + b
print("Element-wise addition (a + b):", sum_array)

# Multiply two NumPy arrays element by element
product_array = a * b
print("Element-wise multiplication (a * b):", product_array)

Element-wise addition (a + b): [5 7 9]
Element-wise multiplication (a * b): [ 4 10 18]
